### ISSUE TITLE
Build error in v1.17.0

### ISSUE THREAD

**Issue by UDK** [Playgama/bridge-unity#2]
![image](https://github.com/user-attachments/assets/0b91df7f-db19-4ec7-b47e-63b1b6a0b6d8)
When starting the build creation, it gives the following error. If you delete a section when it was created, it will be fine.

**Comment by sergei-playgama** [comment]
You need to fill in all the fields in the player settings, or put dashes. If Unity does not allow you to put a dash, switch to another template and select the Bridge again.
<img width="727" alt="Screenshot 2024-10-31 at 9 14 58 AM" src="https://github.com/user-attachments/assets/7fb837ca-3da0-48df-958e-b887e6929fa2">
